name: Package and Release Extension

on:
  push:
    branches: [ main ]
  workflow_dispatch: #WORK PLEASE

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip D&DScraper folder
      run: |
        cd ${{ github.workspace }}/D\&DScraper
        zip -r ../D\&DScraper.zip ./*

    - name: Get current version from version.json
      id: get_version
      uses: jaywcjlove/github-action-read-file@main
      with:
        path: D&DScraper/version.json

    - name: Extract version
      id: extract_version
      run: echo "::set-output name=version::$(echo '${{ steps.get_version.outputs.content }}' | jq -r '.latestVersion')"

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: v${{ steps.extract_version.outputs.version }}
        name: Release v${{ steps.extract_version.outputs.version }}
        body: |
          Automated release of the D&D Spell Printer extension.
          Includes the latest changes from the main branch.
        artifacts: D\&DScraper.zip
        artifactContentType: application/zip
        draft: false
        prerelease: false